name: 'python action'

on:
  schedule:
    - cron: '1 1-8 * * 1-5'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v3
      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: 'sendDingding'
        run: python pytest.py
